### ISSUE TITLE
make[1]: Leaving directory `/root/v4l2grab'

### ISSUE THREAD

**Issue by tinashemudavanhu** [twam/v4l2grab#11]
When running make, i get the following error;

root@beaglebone:~/v4l2grab# make
make  all-am
make[1]: Entering directory `/root/v4l2grab'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT v4l2grab.o -MD -MP -MF .deps/v4l2grab.Tpo -c -o v4l2grab.o v4l2grab.c
mv -f .deps/v4l2grab.Tpo .deps/v4l2grab.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT yuv.o -MD -MP -MF .deps/yuv.Tpo -c -o yuv.o yuv.c
mv -f .deps/yuv.Tpo .deps/yuv.Po
gcc  -g -O2   -o v4l2grab v4l2grab.o yuv.o  -lv4l2 -ljpeg 
make[1]: Leaving directory`/root/v4l2grab'

I am installing it on BeagleBone Black Rev C running Debian Wheezy, 3.8.13-bone79.

**Comment by twam** [comment]
I cannot see any errors. :(

**Comment by tinashemudavanhu** [comment]
Is there some solution to it. It doesn't look like that make part has been
completed.

**Comment by twam** [comment]
The last line make executes is
`gcc -g -O2 -o v4l2grab v4l2grab.o yuv.o -lv4l2 -ljpeg`
and no error is shown. So I would suspect that everything went fine and you should have a `v4l2grab` binary in the folder. Why do you think that something went wrong?

**Comment by tinashemudavanhu** [comment]
I assumed those make [1] [2] imply something wrong. I have seen it while
installing other packages, i.e opencv and libjpeg-turbo-1.3.0.

**Comment by twam** [comment]
Issue seems to be only a problem of understanding the make output and thus no issue of v4l2grab.
